import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author luisf
 */
public class TelaCad extends javax.swing.JFrame {
    private GerProduto gerProduto = new GerProduto();
    private Produto produto;
    private Venda venda;
    private GerVenda gerVenda = new GerVenda();
    
    
    
    /**
     * Creates new form TelaCad
     */
    public TelaCad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodBarras = new javax.swing.JLabel();
        ctCodBarras = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        ctNome = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        ctPreco = new javax.swing.JTextField();
        lblQuantidade = new javax.swing.JLabel();
        ctQuantidade = new javax.swing.JTextField();
        btCadastrar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCadastro = new javax.swing.JTable();
        btVoltar = new javax.swing.JButton();
        btAdVenda = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVenda = new javax.swing.JTable();
        cbPagamento = new javax.swing.JComboBox<>();
        btVender = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produtos");

        lblCodBarras.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCodBarras.setText("Código de Barras:");

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNome.setText("Nome:");

        lblPreco.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPreco.setText("Preço:");

        lblQuantidade.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblQuantidade.setText("Quantidade:");

        ctQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctQuantidadeActionPerformed(evt);
            }
        });

        btCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btCadastrar.setText("CADASTRAR");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btLimpar.setText("LIMPAR");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btAlterar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btAlterar.setText("ALTERAR");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btExcluir.setText("EXCLUIR");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btConsultar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btConsultar.setText("CONSULTAR");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        tblCadastro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Preço", "Estoque"
            }
        ));
        jScrollPane1.setViewportView(tblCadastro);

        btVoltar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btVoltar.setText("VOLTAR");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        btAdVenda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btAdVenda.setText("ADICIONAR A LISTA DE VENDA");
        btAdVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdVendaActionPerformed(evt);
            }
        });

        tblVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblVenda);

        cbPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cartão", "Dinheiro", " " }));
        cbPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPagamentoActionPerformed(evt);
            }
        });

        btVender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btVender.setText("VENDER");
        btVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPreco)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ctPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(lblQuantidade)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ctQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btLimpar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btAlterar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btExcluir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btConsultar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btAdVenda)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblCodBarras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ctCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(lblNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ctNome, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cbPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btVender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar)
                    .addComponent(btAlterar)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btVender))
                    .addComponent(btVoltar))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(812, 691));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ctQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctQuantidadeActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        alterar();
        listarTab();
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        voltar();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        try {
            Connection con;
            Statement st;
            
            Class.forName("org.postgresql.Driver");
            con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/Produtos","postgres","2212");
            st = con.createStatement();
            st.executeUpdate("insert into produto values('"+ctCodBarras.getText()+"', '"+ctNome.getText()+"', "+Float.parseFloat(ctPreco.getText())+", "+Integer.parseInt(ctQuantidade.getText())+")");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Driver nao encontrado", "mensagem", 0);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "erro na conexao com banco de dados", "mensagem", 0);
        }
        
        cadastrar();
        listarTab();
        limpar();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        try {
            Connection con;
            Statement st;
            
            Class.forName("org.postgresql.Driver");
            con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/Produtos","postgres","2212");
            st = con.createStatement();
            st.executeUpdate("delete from produto where codbarras = '"+ctCodBarras.getText()+"'");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Driver nao encontrado", "mensagem", 0);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "erro na conexao com banco de dados", "mensagem", 0);
        }
        
        excluir();
        listarTab();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        consultar();
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btAdVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdVendaActionPerformed
        adVenda();
        listarTabVenda();
        listarTab();
        limpar();
    }//GEN-LAST:event_btAdVendaActionPerformed

    private void cbPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPagamentoActionPerformed
        cbPagamento.getSelectedIndex();
    }//GEN-LAST:event_cbPagamentoActionPerformed

    private void btVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVenderActionPerformed
        vender();
        limparListaVenda();
        listarTabVenda();
    }//GEN-LAST:event_btVenderActionPerformed

    public void limparListaVenda() {
        gerVenda.bdVenda.clear();
    }
    
    public void vender() {
        venda = new Venda();
        
        if(cbPagamento.getSelectedIndex() == 0) {
            for(int i = 0; i < gerVenda.bdVenda.size(); i++) {
                venda.setValorTotal(venda.getValorTotal() + gerVenda.bdVenda.get(i).getPreco());
            }
            JOptionPane.showMessageDialog(null, "Valor total: "+venda.getValorTotal(), "Venda", 1);
            JOptionPane.showMessageDialog(null, "Venda Realizada com sucesso!!!", "Venda", 1);
        }
        
        if(cbPagamento.getSelectedIndex() == 1) {
            for(int i = 0; i < gerVenda.bdVenda.size(); i++) {
                venda.setValorTotal(venda.getValorTotal() + gerVenda.bdVenda.get(i).getPreco());
            }
            venda.setNota(Float.parseFloat(JOptionPane.showInputDialog(null, "Valor total: "+venda.getValorTotal()+
                    "\nDigite a nota dada pelo cliente:",
                    "Troco", 1)));
            venda.setTroco(venda.getNota() - venda.getValorTotal());
            JOptionPane.showMessageDialog(null, "Troco: "+venda.getTroco(), "Mensagem", 1);
            JOptionPane.showMessageDialog(null, "Venda Realizada com sucesso!!!", "Venda", 1);
        }
    }
    
    public void listarTabVenda() {
        DefaultTableModel modelo = (DefaultTableModel)tblVenda.getModel();
        int lin = 0;
        
        modelo.setRowCount(lin);
        
        for(Venda venda : gerVenda.getVenda()) {
            modelo.insertRow(lin, new Object [] {venda.getCodBarras(), venda.getNome(), venda.getPreco(), venda.getQuantidade()});
            lin++;
        }
    }
    
    public void adVenda() {
        produto = new Produto();
        venda = new Venda();
        
        produto.setCodBarras(ctCodBarras.getText());
        for(int i = 0; i < gerProduto.bdProduto.size(); i++) {
            if(produto.getCodBarras().equals(gerProduto.bdProduto.get(i).getCodBarras())) {
                int quant = Integer.parseInt(JOptionPane.showInputDialog(null, "Digite a quantidade de itens a serem vendidos: ", "Venda", 1));
                gerProduto.bdProduto.get(i).setEstoque(gerProduto.bdProduto.get(i).getEstoque() - quant);
                venda.setCodBarras(gerProduto.bdProduto.get(i).getCodBarras());
                venda.setQuantidade(quant);
                venda.setNome(gerProduto.bdProduto.get(i).getNome());
                venda.setPreco(gerProduto.bdProduto.get(i).getPreco() * (float)quant);
                venda = gerVenda.cadVenda(venda);
                
                if(venda != null) {
                    JOptionPane.showMessageDialog(null, "Produto adicionado a lista de venda!!!", "Mensagem", 1);
                }
            }
        } 
    }
    
    public void listarTab() {
        DefaultTableModel modelo = (DefaultTableModel)tblCadastro.getModel();
        int lin = 0;
        
        modelo.setRowCount(lin);
        
        for(Produto produto : gerProduto.getProduto()) {
            modelo.insertRow(lin, new Object [] {produto.getCodBarras(), produto.getNome(), produto.getPreco(), produto.getEstoque()});
            lin++;
        }
    }
    
    public void consultar() {
        produto = new Produto();
        
        String resp = JOptionPane.showInputDialog(null,  "Digite o código de barras do produto a ser consultado:", "Consultar", 1);
        produto.setCodBarras(resp);
        for(int i = 0; i < gerProduto.bdProduto.size(); i++) {
            if(produto.getCodBarras().equals(gerProduto.bdProduto.get(i).getCodBarras())) {
                produto.setCodBarras(gerProduto.bdProduto.get(i).getCodBarras());
                produto.setNome(gerProduto.bdProduto.get(i).getNome());
                produto.setPreco(gerProduto.bdProduto.get(i).getPreco());
                produto.setEstoque(gerProduto.bdProduto.get(i).getEstoque());
                
                JOptionPane.showMessageDialog(null,"Produto: "+produto.getNome()+"\nCódigo de Barras: "+produto.getCodBarras()+"\nPreço: "+produto.getPreco()+
                        "\nEstoque: "+produto.getEstoque(), "Consultar", 1);
            }
        }
    }
    
    public void excluir() {
        produto = new Produto();
        
        produto.setCodBarras(ctCodBarras.getText());
        for(int i = 0; i < gerProduto.bdProduto.size(); i++) {
            if(produto.getCodBarras().equals(gerProduto.bdProduto.get(i).getCodBarras())) {
                gerProduto.bdProduto.remove(i);
                JOptionPane.showMessageDialog(null, "Produto excluído com sucesso!!!", "Mensagem", 1);
            }
        }
    }
    
    public void alterar() {
        String resp;
        produto = new Produto();
        
        produto.setCodBarras(ctCodBarras.getText());
        for(int i = 0; i < gerProduto.bdProduto.size(); i++) {
            if(produto.getCodBarras().equals(gerProduto.bdProduto.get(i).getCodBarras())) {
                String nome = JOptionPane.showInputDialog(null, "Digite o novo nome:", "Alteração de dados", 1);
                produto.setNome(nome);
                int quant = Integer.parseInt(JOptionPane.showInputDialog(null, "Digite a nova quantidade:", "Alteração de dados", 1));
                produto.setEstoque(quant);
                float preco = Float.parseFloat(JOptionPane.showInputDialog(null, "Digite o novo preço:", "Alteração de dados", 1));
                produto.setPreco(preco);
                
                produto.setCodBarras(gerProduto.bdProduto.get(i).getCodBarras());
                gerProduto.bdProduto.set(i, produto);
            }
        }
        JOptionPane.showMessageDialog(null, "Dados do produto alterados com sucesso!!!", "Alteração de Dados", 1);
        limpar();
    }
    
    public void cadastrar() {
        produto = new Produto();
        
        produto.setCodBarras(ctCodBarras.getText());
        produto.setNome(ctNome.getText());
        produto.setQuantidade(Integer.parseInt(ctQuantidade.getText()));
        produto.setPreco(Float.parseFloat(ctPreco.getText()));
        produto.setEstoque(produto.getEstoque() + produto.getQuantidade());
        
        produto = gerProduto.cadProduto(produto);
        if(produto != null) {
            JOptionPane.showMessageDialog(null, "Produto cadastrado com sucesso!!!", "Cadastro de Produto", 1);
        }
    }
    
    public void voltar() {
        int resp = JOptionPane.showConfirmDialog(null, "Deseja Voltar para o menu?", "Voltar", 1);
        if(resp == 0) {
            this.setVisible(false);
            Menu menu = new Menu();
            menu.setVisible(true);
        }
    }
    
    public void limpar() {
        ctCodBarras.setText("");
        ctNome.setText("");
        ctQuantidade.setText("");
        ctPreco.setText("");
        ctCodBarras.requestFocus();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdVenda;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btVender;
    private javax.swing.JButton btVoltar;
    private javax.swing.JComboBox<String> cbPagamento;
    private javax.swing.JTextField ctCodBarras;
    private javax.swing.JTextField ctNome;
    private javax.swing.JTextField ctPreco;
    private javax.swing.JTextField ctQuantidade;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCodBarras;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JTable tblCadastro;
    private javax.swing.JTable tblVenda;
    // End of variables declaration//GEN-END:variables
}
